#!/usr/bin/perl
# encoding: utf-8
# author: Jinxin Meng
# created date: 2023-04-01, 01:51:07
# modified date: 2024-02-16, 01:51:07
# For genome comparison across multiple catalog, parse cls_info by signature provided by users.
use strict;
use warnings;

die "Usage: perl $0 [dRep_res generated by parse_dRep.pl] [sig_list] [out_file]\n Signatures is character in a comma-delimited format.\n" unless @ARGV eq 3;
my ($in_f, $sig ,$out) = @ARGV;

open O, ">$out"; 
my @s = split /,/, $sig;
print O "cluster\t".join("\t", @s)."\n";

open I, "<$in_f" or die "Can't open $in_f: $!\n";
while(<I>){
    chomp;
    my @s2 = split /\t/, $_;
    my @s3 = split /,/, $s2[-1];
    my %h;
    for my $i (@s) {
        $h{$i} = 0;
    }
    for my $i (@s3) {
        for my $r (@s) {
            if ($i =~ /$r/) {
                $h{$r} = $h{$r} + 1;
            }
        }
    }

    my @l;
    for my $i (@s) {
        push @l, $h{$i};
    }
    print O "$s2[0]\t".join("\t", @l)."\n";
}
